# Generated by Django 3.1.1 on 2020-10-15 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('char_code', models.CharField(db_index=True, max_length=3)),
                ('value', models.FloatField(verbose_name='Value')),
                ('date_update', models.DateField(verbose_name='Updated')),
                ('nominal', models.IntegerField(default=1, verbose_name='Nominal')),
                ('nominal_value', models.FloatField(default=0, verbose_name='Nominal Value')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'unique_together': {('char_code', 'date_update')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3)),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.userprofile')),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
