# Generated by Django 3.1.1 on 2020-10-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3)),
                ('wallet_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcoming_transactions', to='wallet.wallet')),
                ('wallet_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='wallet.wallet')),
            ],
        ),
    ]
